channels:
- conda-forge
- nodefaults
dependencies:
# - python ==3.10
# - pip >=23
# - jupyterlab
# - jupyterhub
- jupyterlab-language-pack-zh-CN
# - notebook
- ipywidgets==7.6.6
# - digautoprofiler # nothing provides requested digautoprofiler
- jupyterlab-cell-flash
- numpy
- sympy
- scipy
- matplotlib
- seaborn
- pandas
# pandasgui
- Pillow
- hiplot
- requests
- beautifulsoup4
- fastapi
- aiohttp
- Scrapy