channels:
- conda-forge
- nodefaults
dependencies:
- python >=3.10,<3.12
- pip >=23,<24
- jupyterlab >=3.6,<3.7
- jupyterhub-singleuser >=3.1.1,<4
- notebook
- jupyterlab-language-pack-zh-CN
- ipywidgets ==7.6.6