name: Build Notebook Container
on:
  workflow_dispatch:
  push:
    branches:
      - main--DISABLE
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@master

    - name: update jupyter dependencies with repo2docker
      uses: machine-learning-apps/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        BINDER_CACHE: true # It appears that “MYBINDERORG_CACHE” has been renamed “BINDER_CACHE”.